home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

lab_formtest:
    resource: "@LabFormtestBundle/Controller/"
    type:     annotation
    prefix:   /lab

lab_configtest:
    resource: "@LabConfigtestBundle/Controller/"
    type:     annotation
    prefix:   /lab

lab_serializertest:
    resource: "@LabSerializertestBundle/Controller/"
    type:     annotation
    prefix:   /lab